import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'settings/app_theme.dart';
import 'splash_page.dart';
import 'settings/app_strings.dart'; // S localization class

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const CleaningApp());
}

class CleaningApp extends StatefulWidget {
  const CleaningApp({super.key});

  /// This lets you do CleaningApp.of(context) anywhere
  static _CleaningAppState of(BuildContext context) {
    final state = context.findAncestorStateOfType<_CleaningAppState>();
    assert(state != null, 'CleaningApp.of(context) called outside CleaningApp');
    return state!;
  }

  @override
  State<CleaningApp> createState() => _CleaningAppState();
}

class _CleaningAppState extends State<CleaningApp> {
  ThemeMode _themeMode = ThemeMode.light;
  Locale _locale = const Locale('en');

  ThemeMode get themeMode => _themeMode;
  Locale get locale => _locale;

  void toggleTheme() {
    setState(() {
      _themeMode =
      _themeMode == ThemeMode.light ? ThemeMode.dark : ThemeMode.light;
    });
  }

  void toggleLocale() {
    setState(() {
      _locale =
      _locale.languageCode == 'en' ? const Locale('ar') : const Locale('en');
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Cleaning Services',
      debugShowCheckedModeBanner: false,

      // light / dark themes
      theme: buildLightTheme(),
      darkTheme: buildDarkTheme(),
      themeMode: _themeMode,

      // localization
      locale: _locale,
      supportedLocales: const [
        Locale('en'),
        Locale('ar'),
      ],
      localizationsDelegates: const [
        S.delegate, // your custom strings
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],

      // force LTR layout even for Arabic (only text changes)
      builder: (context, child) {
        return Directionality(
          textDirection: TextDirection.ltr,
          child: child ?? const SizedBox.shrink(),
        );
      },

      home: const SplashPage(),
    );
  }
}
